# Generated by Django 5.1.4 on 2025-01-15 12:01

import server.apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Не обязательное поле', max_length=25, null=True, verbose_name='Название')),
                ('card_number', models.CharField(max_length=16, validators=[server.apps.accounts.validators.validate_card_number], verbose_name='Номер карты')),
                ('phone_number', models.CharField(max_length=11, validators=[server.apps.accounts.validators.validate_phone_number], verbose_name='Номер телефона')),
                ('temporary_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='Одноразовый код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_active', models.BooleanField(default=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('has_temporary_code', models.BooleanField(default=False)),
                ('is_errored', models.BooleanField(default=False)),
                ('session_cookies', models.TextField(blank=True, null=True, verbose_name='Cookies session')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Google user agent')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
                'ordering': ['-created_at', 'is_active', '-is_errored', 'is_authenticated'],
            },
        ),
    ]
