# Generated by Django 5.1.4 on 2025-01-04 15:34

from django.db import migrations, models

import server.apps.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_number',
            field=models.CharField(max_length=16, validators=[server.apps.accounts.validators.validate_card_number], verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[server.apps.accounts.validators.validate_phone_number], verbose_name='Номер телефона'),
        ),
    ]
