# Generated by Django 5.1.4 on 2025-01-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='audio_fingerprint',
            field=models.TextField(blank=True, null=True, verbose_name='Аудио fingerprint'),
        ),
        migrations.AddField(
            model_name='account',
            name='battery_level',
            field=models.FloatField(blank=True, null=True, verbose_name='Уровень заряда батареи'),
        ),
        migrations.AddField(
            model_name='account',
            name='canvas_fingerprint',
            field=models.TextField(blank=True, null=True, verbose_name='Canvas fingerprint'),
        ),
        migrations.AddField(
            model_name='account',
            name='cpu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Процессор'),
        ),
        migrations.AddField(
            model_name='account',
            name='device_memory',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Объём памяти (GB)'),
        ),
        migrations.AddField(
            model_name='account',
            name='gpu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Видеокарта'),
        ),
        migrations.AddField(
            model_name='account',
            name='hardware_concurrency',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество логических процессоров'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_charging',
            field=models.BooleanField(blank=True, null=True, verbose_name='Зарядка подключена'),
        ),
        migrations.AddField(
            model_name='account',
            name='local_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Локальный IP'),
        ),
        migrations.AddField(
            model_name='account',
            name='navigator_platform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Платформа браузера'),
        ),
        migrations.AddField(
            model_name='account',
            name='public_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Публичный IP'),
        ),
        migrations.AddField(
            model_name='account',
            name='screen_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота экрана (px)'),
        ),
        migrations.AddField(
            model_name='account',
            name='screen_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина экрана (px)'),
        ),
        migrations.AddField(
            model_name='account',
            name='webgl_renderer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='WebGL Renderer'),
        ),
        migrations.AddField(
            model_name='account',
            name='webgl_vendor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='WebGL Vendor'),
        ),
    ]
