# Generated by Django 5.1.4 on 2025-01-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_card_number_alter_account_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['created_at', 'is_active'], 'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
    ]
