# Generated by Django 5.1.4 on 2025-01-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created_at', 'is_active'], 'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.AddField(
            model_name='account',
            name='has_temporary_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='session_cookies',
            field=models.TextField(blank=True, null=True, verbose_name='Cookies сессии'),
        ),
        migrations.AddField(
            model_name='account',
            name='temporary_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Одноразовый код'),
        ),
    ]
