# Generated by Django 5.1.4 on 2025-01-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_options_account_has_temporary_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created_at', 'is_active', 'has_temporary_code', 'is_authenticated'], 'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.AddField(
            model_name='account',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
