# Generated by Django 5.1.4 on 2025-01-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_options_account_is_authenticated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created_at', 'is_active', '-is_errored', 'is_authenticated'], 'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.AddField(
            model_name='account',
            name='is_errored',
            field=models.BooleanField(default=False),
        ),
    ]
