version: "3.7"

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - static_volume:/app/src/server/static/
      - media_volume:/app/src/server/media/

  nginx:
    build:
      context: .
      dockerfile: ./deploy/nginx/Dockerfile.nginx
    command: nginx -g 'daemon off;'
    volumes:
      - static_volume:/app/src/server/static/
      - media_volume:/app/src/server/media/
    depends_on:
      - db
      - web

  nginx_proxy_pass:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginx_data:/data
      - letsencrypt_data:/etc/letsencrypt



volumes:
  pg_data:
  static_volume:
  media_volume:
  nginx_data:
  letsencrypt_data: