services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    restart: on-failure
    env_file:
      - .env
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: on-failure
    volumes:
      - static_volume:/app/src/server/static/
      - media_volume:/app/src/server/media/

  celery: &celery
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: celery -A src.server.settings worker -l info
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web

  celery_beat:
    <<: *celery
    entrypoint: celery -A src.server.settings beat -l info

  nginx:
    build:
      context: .
      dockerfile: ./deploy/nginx/Dockerfile.nginx
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - static_volume:/app/src/server/static/
      - media_volume:/app/src/server/media/
    depends_on:
      - db
      - web

volumes:
  pg_data:
  static_volume:
  media_volume: